FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm@10.28.2

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 4200

CMD ["npx", "nx", "serve", "web", "--host", "0.0.0.0", "--port", "4200"]
