// <auto-generated />
using System;
using BetterTests.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetterTests.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304160927_CreateInitialSchema")]
    partial class CreateInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetterTests.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name_unique");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Postconditions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("postconditions");

                    b.Property<string>("Preconditions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("preconditions");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("suite_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_test_cases");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_test_cases_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_test_cases_status");

                    b.HasIndex("SuiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_test_cases_suite_id_name_unique");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestCaseStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("action");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("expected_result");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id")
                        .HasName("pk_test_case_steps");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("ix_test_case_steps_case_id");

                    b.HasIndex("TestCaseId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_test_case_steps_case_id_order_unique");

                    b.ToTable("test_case_steps", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comments");

                    b.Property<string>("DefectLink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("defect_link");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("executed_by");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<Guid?>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_id");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.HasIndex("Result")
                        .HasDatabaseName("ix_test_results_result");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("ix_test_results_test_case_id");

                    b.HasIndex("TestRunId")
                        .HasDatabaseName("ix_test_results_test_run_id");

                    b.HasIndex("TestRunId", "TestCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_test_results_run_id_case_id_unique")
                        .HasFilter("[TestCaseId] IS NOT NULL");

                    b.ToTable("test_results", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("executed_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_test_runs");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_test_runs_project_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_test_runs_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_test_runs_status");

                    b.ToTable("test_runs", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_test_suites");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_test_suites_project_id_name_unique");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("BetterTests.Domain.Entities.TestSuite", "Suite")
                        .WithMany("TestCases")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_cases_test_suites");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestCaseStep", b =>
                {
                    b.HasOne("BetterTests.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_steps_test_cases");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("BetterTests.Domain.Entities.TestCase", "TestCase")
                        .WithMany("TestResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_test_results_test_cases");

                    b.HasOne("BetterTests.Domain.Entities.TestRun", "TestRun")
                        .WithMany("TestResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_results_test_runs");

                    b.Navigation("TestCase");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestRun", b =>
                {
                    b.HasOne("BetterTests.Domain.Entities.Project", "Project")
                        .WithMany("TestRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_runs_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestSuite", b =>
                {
                    b.HasOne("BetterTests.Domain.Entities.Project", "Project")
                        .WithMany("TestSuites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_suites_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.Project", b =>
                {
                    b.Navigation("TestRuns");

                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestRun", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("BetterTests.Domain.Entities.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
